[information]
name="one_light"
author="Ken Zhou <kendotzhou@gmail.com>"
background="light"

[palette]
white = "#54555b"
darker_black = "#efeff0"
black = "#fafafa" #  nvim bg
black2 = "#EAEAEB"
one_bg = "#dadadb" # real bg of onedark
one_bg2 = "#d4d4d5"
one_bg3 = "#cccccd"
grey = "#b7b7b8"
grey_fg = "#b0b0b1"
grey_fg2 = "#a9a9aa"
light_grey = "#a2a2a3"
red = "#d84a3d"
baby_pink = "#F07178"
pink = "#ff75a0"
line = "#e2e2e2" # for lines like vertsplit
green = "#50a14f"
vibrant_green = "#7eca9c"
nord_blue = "#428bab"
blue = "#4078f2"
yellow = "#c18401"
sun = "#dea95f"
purple = "#a28dcd"
dark_purple = "#8e79b9"
teal = "#519ABA"
orange = "#FF6A00"
cyan = "#0b8ec6"
statusline_bg = "#ececec"
lightbg = "#d3d3d3"
pmenu_bg = "#5e5f65"
folder_bg = "#6C6C6C"
base00 = "#fafafa"
base01 = "#f4f4f4"
base02 = "#e5e5e6"
base03 = "#dfdfe0"
base04 = "#d7d7d8"
base05 = "#383a42"
base06 = "#202227"
base07 = "#090a0b"
base08 = "#d84a3d"
base09 = "#a626a4"
base0A = "#c18401"
base0B = "#50a14f"
base0C = "#0070a8"
base0D = "#4078f2"
base0E = "#a626a4"
base0F = "#986801"

[highlights]
Normal = 'base05 base00'
SignColumn = 'base03 - - -'
MsgArea = 'base05 base00'
ModeMsg = 'base0B'
MsgSeparator = 'base05 base00'
SpellBad = '- - c base08'
SpellCap = '- - c base0D'
SpellLocal = '- - c base0C'
SpellRare = '- - c base0D'
NormalNC = 'base05 base00'
Pmenu = '- one_bg'
PmenuSel = 'black pmenu_bg'
WildMenu = 'base08 base0A'
CursorLineNr = 'white'
Comment = 'grey_fg'
Folded = 'base03 base01'
FoldColumn = 'base0C base01'
LineNr = 'grey'
FloatBorder = 'blue'
# Whitespace = 'base00 -'
VertSplit = 'line'
CursorLine = '- base01'
CursorColumn = '- base01'
ColorColumn = '- base01'
NormalFloat = '- darker_black'
Visual = '- base02'
VisualNOS = 'base08 -'
WarningMsg = 'base08'
DiffAdd = 'vibrant_green'
DiffChange = 'blue'
DiffDelete = 'red'
QuickFixLine = '- base01 - -'
PmenuSbar = '- one_bg'
PmenuThumb = '- grey'
MatchWord = 'white grey'
MatchParen = 'link:MatchWord'
# MatchWordCur = '- - u'
# MatchParenCur = '- - u'
Cursor = 'base00 base05'
# lCursor = 'base05 base00'
# CursorIM = 'base05 base00'
# TermCursor = 'base05 base00'
# TermCursorNC = 'base05 base00'
Conceal = '- -'
Directory = 'base0D'
SpecialKey = 'base03'
Title = 'base0D - - -'
ErrorMsg = 'base08 base00'
Search = 'base01 base0A'
IncSearch = 'base01 base09'
Substitute = 'base01 base0A - -'
MoreMsg = 'base0B'
Question = 'base0D'
# EndOfBuffer = 'base00'
NonText = 'base03'
Variable = 'base05'
String = 'base0B'
Character = 'base08'
Constant = 'base08'
Number = 'base09'
Boolean = 'base09'
Float = 'base09'
Identifier = 'base08 - - -'
Function = 'base0D'
Operator = 'base05 - - -'
Type = 'base0A - - -'
StorageClass = 'base0A'
Structure = 'base0E'
Typedef = 'base0A'
Keyword = 'base0E'
Statement = 'base08'
Conditional = 'base0E'
Repeat = 'base0A'
Label = 'base0A'
Exception = 'base08'
Include = 'base0D'
PreProc = 'base0A'
Define = 'base0E - - -'
Macro = 'base08'
# PreCondit = 'purple'
Special = 'base0C'
SpecialChar = 'base0F'
Tag = 'base0A'
Debug = 'base08'
# Delimiter = 'grey -'
# SpecialComment = 'grey_fg'
Underlined = 'base0B'
Bold = '- - b'
Italic = '- - i'
Ignore = 'cyan base00 b'
Todo = 'base0A base01'
Error = 'base00 base08'
TabLine = 'light_grey line'
TabLineSel = 'white line'
TabLineFill = 'line line'

[Treesitter]
"@annotation" = 'base0F'
"@attribute" = 'base0A'
"@constructor" = 'base0C'
#" TSType = 'cyan'
"@type.builtin" = 'base0A'
"@conditional" = 'link:Conditional'
"@exception" = 'base08'
"@include" = 'link:Include'
"@keyword.return" = 'base0E'
"@keyword" = 'base0E'
"@keyword.function" = 'base0E'
#" TSLabel = 'cyan'
"@namespace" = 'base08'
#" TSRepeat = 'yellow'
#" TSConstant = 'orange'
"@constant.builtin" = 'base09'
"@float" = 'base09'
#" TSNumber = 'orange'
#" TSBoolean = 'orange'
"@character" = 'base08'
"@error" = 'base08'
"@function" = 'base0D'
"@function.builtin" = 'base0D'
"@method" = 'base0D'
"@constant.macro" = 'base08'
"@function.macro" = 'base08'
"@variable" = 'base05'
"@variable.builtin" = 'base09'
"@property" = 'base08'
"@field" = 'base0D'
"@parameter" = 'base08'
"@parameter.reference" = 'base05'
"@symbol" = 'base0B'
"@text" = 'base05'
#" "@Operator = 'base05'
"@punctuation.delimiter" = 'base0F'
"@tag.delimiter" = 'base0F'
"@tag.attribute" = 'link:@Property'
"@punctuation.bracket" = 'base0F'
"@punctuation.special" = 'base08'
#" "@String = 'green'
"@string.regex" = 'base0C'
"@string.escape" = 'base0C'
#" "@Tag = 'blue'
"@emphasis" = 'base09'
#" "@Underline = '- - u'
#" "@Title = 'base05 - -'
"@literal" = 'base09'
"@text.uri" = 'base09'
"@keyword.operator" = 'base0E'
#" "@Structure = 'cyan'
"@strong" = '- - b'
#" "@QueryLinterError = 'base09'
"@scope" = '- - b'
TreesitterContext = 'link:CursorLine'

[markdown]
markdownBlockquote = 'green'
markdownCode = 'orange'
markdownCodeBlock = 'orange'
markdownCodeDelimiter = 'orange'
markdownH1 = 'blue'
markdownH2 = 'blue'
markdownH3 = 'blue'
markdownH4 = 'blue'
markdownH5 = 'blue'
markdownH6 = 'blue'
markdownHeadingDelimiter = 'blue'
markdownHeadingRule = 'base05 - b'
markdownId = 'purple'
markdownIdDeclaration = 'blue'
markdownIdDelimiter = 'light_grey'
markdownLinkDelimiter = 'light_grey'
markdownBold = 'blue - b'
markdownItalic = '- - i'
markdownBoldItalic = 'yellow - bi'
markdownListMarker = 'blue'
markdownOrderedListMarker = 'blue'
markdownRule = 'base01'
markdownUrl = 'cyan - u'
markdownLinkText = 'blue'
markdownFootnote = 'orange'
markdownFootnoteDefinition = 'orange'
markdownEscape = 'yellow'

[Whichkey]
WhichKey = 'purple'
WhichKeySeperator = 'green'
WhichKeyGroup = 'blue'
WhichKeyDesc = 'cyan'
WhichKeyFloat = '- base01'

[Git]
SignAdd = 'green'
SignChange = 'blue'
SignDelete = 'red'
GitSignsAdd = 'green'
GitSignsChange = 'blue'
GitSignsDelete = 'red'

[LSP]
DiagnosticError = 'base08'
DiagnosticWarning = 'base09'
DiagnosticHint = 'purple'
DiagnosticWarn = 'yellow'
DiagnosticInfo = 'green'
LspDiagnosticsDefaultError = 'base08'
LspDiagnosticsDefaultWarning = 'base09'
LspDiagnosticsDefaultInformation = 'sun'
LspDiagnosticsDefaultInfo = 'sun'
LspDiagnosticsDefaultHint = 'purple'
LspDiagnosticsVirtualTextError = 'base08'
LspDiagnosticsVirtualTextWarning = 'base09'
LspDiagnosticsVirtualTextInformation = 'sun'
LspDiagnosticsVirtualTextInfo = 'sun'
LspDiagnosticsVirtualTextHint = 'purple'
LspDiagnosticsFloatingError = 'base08'
LspDiagnosticsFloatingWarning = 'base09'
LspDiagnosticsFloatingInformation = 'sun'
LspDiagnosticsFloatingInfo = 'sun'
LspDiagnosticsFloatingHint = 'purple'
DiagnosticSignError = 'base08'
DiagnosticSignWarning = 'base09'
DiagnosticSignInformation = 'sun'
DiagnosticSignInfo = 'sun'
DiagnosticSignHint = 'purple'
LspDiagnosticsSignError = 'base08'
LspDiagnosticsSignWarning = 'base09'
LspDiagnosticsSignInformation = 'sun'
LspDiagnosticsSignInfo = 'sun'
LspDiagnosticsSignHint = 'purple'
LspDiagnosticsError = 'base08'
LspDiagnosticsWarning = 'base09'
LspDiagnosticsInformation = 'sun'
LspDiagnosticsInfo = 'sun'
LspDiagnosticsHint = 'purple'
LspDiagnosticsUnderlineError = '- - u'
LspDiagnosticsUnderlineWarning = '- - u'
LspDiagnosticsUnderlineInformation = '- - u'
LspDiagnosticsUnderlineInfo = '- - u'
LspDiagnosticsUnderlineHint = '- - u'
LspReferenceRead = '- #2e303b'
LspReferenceText = '- #2e303b'
LspReferenceWrite = '- #2e303b'
LspCodeLens = 'base04 - i'
LspCodeLensSeparator = 'base04 - i'

[Telescope]
TelescopeNormal = '- darker_black'
TelescopePreviewTitle = 'black green b'
TelescopePromptTitle = 'black red b'
TelescopeResultsTitle = 'darker_black darker_black b'
TelescopeSelection = 'white black2'
# TelescopeMatching = 'sun - b'
TelescopeBorder = 'darker_black darker_black'
TelescopePromptBorder = 'black2 black2'
TelescopePromptNormal = 'white black2'
TelescopePromptPrefix = 'red black2'
TelescopeResultsDiffAdd = 'green'
TelescopeResultsDiffChange = 'blue'
TelescopeResultsDiffDelete = 'red'

[NvimTree]
NvimTreeFolderIcon = 'blue'
NvimTreeIndentMarker = '#c5c5c5'
NvimTreeNormal = '- darker_black'
NvimTreeVertSplit = 'darker_black darker_black'
NvimTreeFolderName = 'blue'
NvimTreeOpenedFolderName = 'blue - bi'
NvimTreeEmptyFolderName = 'grey - i'
NvimTreeGitIgnored = 'grey - i'
NvimTreeImageFile = 'light_grey'
NvimTreeSpecialFile = 'orange'
NvimTreeEndOfBuffer = 'darker_black'
NvimTreeCursorLine = '- #282b37'
NvimTreeGitignoreIcon = 'red'
NvimTreeGitStaged = 'vibrant_green'
NvimTreeGitNew = 'vibrant_green'
NvimTreeGitRenamed = 'vibrant_green'
NvimTreeGitDeleted = 'red'
NvimTreeGitMerge = 'blue'
NvimTreeGitDirty = 'blue'

NvimTreeSymlink = 'cyan'
NvimTreeRootFolder = 'base05 - b'
NvimTreeExecFile = 'green'

[Buffer]
BufferCurrent = 'base05 base00'
BufferCurrentIndex = 'base05 base00'
BufferCurrentMod = 'sun base00'
BufferCurrentSign = 'purple base00'
BufferCurrentTarget = 'red base00 b'

BufferVisible = 'base05 base00'
BufferVisibleIndex = 'base05 base00'
BufferVisibleMod = 'sun base00'
BufferVisibleSign = 'grey base00'
BufferVisibleTarget = 'red base00 b'

BufferInactive = 'grey darker_black'
BufferInactiveIndex = 'grey darker_black'
BufferInactiveMod = 'sun darker_black'
BufferInactiveSign = 'grey darker_black'
BufferInactiveTarget = 'red darker_black b'

[StatusLine]
StatusLine = 'line statusline_bg'
StatusLineNC = '- statusline_bg'
StatusLineSeparator = 'line'
StatusLineTerm = 'line'
StatusLineTermNC = 'line'

[IndentBlankline]
IndentBlanklineContextChar = 'grey'
IndentBlanklineContextStart = '- one_bg2'
IndentBlanklineChar = 'line'
IndentBlanklineSpaceChar = 'line'
IndentBlanklineSpaceCharBlankline = 'sun'

[Dashboard]
DashboardHeader = 'blue'
DashboardCenter = 'purple'
DashboardFooter = 'cyan'

[Cmp]
CmpItemAbbrDeprecated = 'grey - s'
CmpItemAbbrMatch = 'blue'
CmpItemAbbrMatchFuzzy = 'blue'
CmpItemKindFunction = 'blue'
CmpItemKindMethod = 'blue'
CmpItemKindConstructor = 'cyan'
CmpItemKindClass = 'cyan'
CmpItemKindEnum = 'cyan'
CmpItemKindEvent = 'yellow'
CmpItemKindInterface = 'cyan'
CmpItemKindStruct = 'cyan'
CmpItemKindVariable = 'red'
CmpItemKindField = 'red'
CmpItemKindProperty = 'red'
CmpItemKindEnumMember = 'orange'
CmpItemKindConstant = 'orange'
CmpItemKindKeyword = 'purple'
CmpItemKindModule = 'cyan'
CmpItemKindValue = 'base05'
CmpItemKindUnit = 'base05'
CmpItemKindText = 'base05'
CmpItemKindSnippet = 'yellow'
CmpItemKindFile = 'base05'
CmpItemKindFolder = 'base05'
CmpItemKindColor = 'base05'
CmpItemKindReference = 'base05'
CmpItemKindOperator = 'base05'
CmpItemKindTypeParameter = 'red'

[ToggleTerm]
ToggleTerm1FloatBorder = 'line'

[Illuminate]
IlluminatedWordText = '- base02 - -'
IlluminatedWordRead = '- base02 - -'
